version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
               ## - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                ##- not_null
                
    - name: customers_test
      description: "A starter dbt model with customer table"
      columns:
          - name: id
            description: Identificador único del cliente.
            tests:
            - not_null
            #- unique
          - name: first_name
            description: Nombre del cliente.
          - name: last_name
            description: Apellido del cliente.
          - name: email
            description: Correo electrónico del cliente.
          - name: age
            description: Edad del cliente.
          - name: city
            description: Ciudad de residencia del cliente.